# Third peer of Eureka server cluster
spring:
  application:
    name: eureka-server

server:
  port: 8763

eureka:
  instance:
    hostname: third-peer
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://first-peer:8761/eureka/,http://second-peer:8762/eureka/