server:
  port: 8093
spring:
  application:
    name: feign-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      feign-demo-client:
        connectTimeout: 5000
        # readTimeout: 5000
        loggerLevel: full
        # errorDecoder: com.example.SimpleErrorDecoder
        # retryer: com.example.SimpleRetryer
        # requestInterceptors:
        #  - com.example.FooRequestInterceptor
        # - com.example.BarRequestInterceptor
        decode404: false
        # encoder: com.example.SimpleEncoder
        # decoder: com.example.SimpleDecoder
        # contract: com.example.SimpleContract
      #default:
       # connectTimeout: 5000
        #  readTimeout: 5000
         # loggerLevel: basic
    #default-to-properties: false


